import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:smartmachine365/flutter_flow/flutter_flow_theme.dart';

import 'report_panel_widget.dart';

/// Bottom-of-report bar: data notes, data source/last-updated, and the
/// "Report Generated By" brand mark.
class ReportFooterBar extends StatelessWidget {
  final List<String> notes;
  final String dataSourceLabel;
  final String lastUpdatedLabel;
  final String generatedByLabel;

  /// Optional configured override (see md_insight_report_image_config.dart)
  /// — when set, this network image replaces the bundled SF365 logo asset.
  final String? logoImageUrl;

  const ReportFooterBar({
    super.key,
    required this.notes,
    required this.dataSourceLabel,
    required this.lastUpdatedLabel,
    required this.generatedByLabel,
    this.logoImageUrl,
  });

  @override
  Widget build(BuildContext context) {
    final theme = FlutterFlowTheme.of(context);
    return ReportPanel(
      builder: (context, sizing) {
        return LayoutBuilder(builder: (context, constraints) {
          final isWide = constraints.maxWidth > 800;
          final notesBlock = Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: [
              Text('Notes:',
                  style: GoogleFonts.poppins(
                      fontSize: 14,
                      fontWeight: FontWeight.w700,
                      color: theme.primaryText)),
              const SizedBox(height: 6),
              for (final n in notes)
                Text(n,
                    style: GoogleFonts.poppins(
                        fontSize: 13.5, color: theme.secondaryText)),
            ],
          );
          final dataSourceBlock = Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(Icons.storage_rounded, size: 28, color: theme.secondaryText),
              const SizedBox(width: 12),
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text('Data Source:',
                      style: GoogleFonts.poppins(
                          fontSize: 13.5, color: theme.secondaryText)),
                  Text(dataSourceLabel,
                      style: GoogleFonts.poppins(
                          fontSize: 14.5,
                          fontWeight: FontWeight.w600,
                          color: theme.primaryText)),
                  Text(lastUpdatedLabel,
                      style: GoogleFonts.poppins(
                          fontSize: 13.5, color: theme.secondaryText)),
                ],
              ),
            ],
          );
          final brandBlock = Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              Column(
                crossAxisAlignment: CrossAxisAlignment.end,
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text('Report Generated By:',
                      style: GoogleFonts.poppins(
                          fontSize: 13.5, color: theme.secondaryText)),
                  Text(generatedByLabel,
                      style: GoogleFonts.poppins(
                          fontSize: 14.5,
                          fontWeight: FontWeight.w600,
                          color: theme.primaryText)),
                ],
              ),
              const SizedBox(width: 12),
              (logoImageUrl != null && logoImageUrl!.isNotEmpty)
                  ? Image.network(
                      logoImageUrl!,
                      height: 68,
                      fit: BoxFit.contain,
                      errorBuilder: (context, error, stackTrace) => Image.asset(
                        'assets/images/sf365-logo.png',
                        height: 68,
                        fit: BoxFit.contain,
                      ),
                    )
                  : Image.asset('assets/images/sf365-logo.png',
                      height: 68, fit: BoxFit.contain),
            ],
          );

          if (!isWide) {
            return Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  notesBlock,
                  const SizedBox(height: 16),
                  dataSourceBlock,
                  const SizedBox(height: 16),
                  brandBlock
                ]);
          }
          // Three even columns (not notes-dominant) so Data Source and the
          // brand mark get equal visual weight, matching the design mock.
          return Row(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Expanded(
                  child: Align(
                      alignment: Alignment.centerLeft, child: notesBlock)),
              Container(
                  width: 1,
                  height: 40,
                  color: theme.alternate,
                  margin: const EdgeInsets.symmetric(horizontal: 16)),
              Expanded(
                  child: Align(
                      alignment: Alignment.center, child: dataSourceBlock)),
              Container(
                  width: 1,
                  height: 40,
                  color: theme.alternate,
                  margin: const EdgeInsets.symmetric(horizontal: 16)),
              Expanded(
                  child: Align(
                      alignment: Alignment.centerRight, child: brandBlock)),
            ],
          );
        });
      },
    );
  }
}
